### ISSUE TITLE
gtk-test does not show window

### ISSUE THREAD

**Issue by oivulf** [Ramarren/cells-gtk3#1]
Hallo gtk-test:gtk-demo does not show window.
The reason is gtk_init gets never called.
Infact, calling gtk-init-check before gtk-demo shows the demo window.
gtk: 2.24.10
sbcl: 1.0.57.0.debian (but the same applies to other lisps)

(g-thread-get-initialized) always returns t here

**Comment by Ramarren** [comment]
Unfortunately, cells-gtk is lagging quite heavily relative to current GTK+, but I don't really have time to fix it. This change at least makes the window start up.
